libwpa_client is declared as LOCAL_MODULE = libwpa_client instead of with the :=
error: external/wpa_supplicant_8/wpa_supplicant: MODULE.TARGET.SHARED_LIBRARIES.libwpa_client already defined by vendor/motorola/fogo.