error: vendor/qcom/opensource/usb/etc: MODULE.TARGET.ETC.init.qcom.usb.rc already defined by device/motorola/fogo/rootdir.
error: vendor/qcom/opensource/usb/etc: MODULE.TARGET.EXECUTABLES.init.qcom.usb.sh already defined by device/motorola/fogo/rootdir.

error: hardware/qcom-caf/sm8350/display/init: MODULE.TARGET.EXECUTABLES.init.qti.display_boot.sh already defined by device/motorola/fogo/rootdir.

module "init.qcom.usb.rc" variant "android_arm64_armv8-a": module source path "device/motorola/fogo/rootdir/etc/init.qcom.usb.rc" does not exist